name: SimplestHomes
description: The simplest homes command possible
version: 0.1.0
author: Robin de Graaf
main: com.devvoh.simplesthomes.SimplestHomesPlugin
api-version: 1.16
commands:
  home:
    description: Go to homes
  sethome:
    description: Set homes